public class Project1 {
    
}
/*  
    Name: Garrett Dodd
    Student ID: L0071506
    Email: gdodd1@una.edu
    Course Information: <CS 315>
    Program Source File Name: Project1.java
    Programming Assignment:  #1 
    Program Description: Book Form Entry GUI
    References: 
    Due Date:     11 April 2022
 
   In keeping with the honor code policies of the University of University of North Alabama, 
the School of Business, and the Department of Computer Science, I affirm that I have 
neither given nor received on this programming assignment. This assignment
represents my individual, original effort.
 ... My Signature is on File.
         
*/ 

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author garrettdodd
 */
public class Project1 extends javax.swing.JFrame {

    /**
     * Creates new form Project1
     */
    public Project1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        BookFormLBL = new javax.swing.JLabel();
        BookIDLBL = new javax.swing.JLabel();
        IDInput = new javax.swing.JTextField();
        TitleLBL = new javax.swing.JLabel();
        TitleInput = new javax.swing.JTextField();
        AuthorLBL = new javax.swing.JLabel();
        AuthorInput = new javax.swing.JTextField();
        PublisherLBL = new javax.swing.JLabel();
        PublisherInput = new javax.swing.JTextField();
        YearLBL = new javax.swing.JLabel();
        YearInput = new javax.swing.JTextField();
        processButton = new javax.swing.JButton();
        GenreLBL = new javax.swing.JLabel();
        GenreInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BookTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BookFormLBL.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        BookFormLBL.setText("BOOK FORM");

        BookIDLBL.setText("Book ID:");

        IDInput.setText(" ");
        IDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDInputActionPerformed(evt);
            }
        });

        TitleLBL.setText("Title: ");

        TitleInput.setText(" ");

        AuthorLBL.setText("Author:");

        PublisherLBL.setText("Publisher:");

        YearLBL.setText("Year:");

        processButton.setText("Process");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        GenreLBL.setText("Genre:");

        BookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {" ", null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Book ID", "Title", "Author", "Genre", "Publisher", "Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BookTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BookIDLBL)
                                    .addGap(70, 70, 70)
                                    .addComponent(IDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GenreLBL)
                                            .addComponent(PublisherLBL))
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GenreInput)
                                            .addComponent(PublisherInput)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AuthorLBL)
                                            .addComponent(TitleLBL))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TitleInput, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                                            .addComponent(AuthorInput)))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(YearLBL)
                                    .addGap(32, 32, 32)
                                    .addComponent(YearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(BookFormLBL)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BookFormLBL)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(YearLBL)
                            .addComponent(YearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(processButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BookIDLBL)
                            .addComponent(IDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TitleLBL)
                            .addComponent(TitleInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AuthorLBL)
                            .addComponent(AuthorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenreLBL)
                            .addComponent(GenreInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PublisherLBL)
                            .addComponent(PublisherInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void IDInputActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        // Counts number of entries
        
        int counter = 0;
        while(BookTable.getModel().getValueAt(counter, 0) != " "){
            counter++;
        }
        
        // Gets input
        
        String input[] = {IDInput.getText(), TitleInput.getText(), AuthorInput.getText(), GenreInput.getText(), PublisherInput.getText(), YearInput.getText()};
        
        // Documents input in table
        
        for(int i=0; i<input.length; i++){
            BookTable.getModel().setValueAt(input[i], counter, i);
        }
        
        IDInput.setText("");
        TitleInput.setText("");
        AuthorInput.setText("");
        GenreInput.setText("");
        PublisherInput.setText("");
        YearInput.setText("");
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField AuthorInput;
    private javax.swing.JLabel AuthorLBL;
    private javax.swing.JLabel BookFormLBL;
    private javax.swing.JLabel BookIDLBL;
    private javax.swing.JTable BookTable;
    private javax.swing.JTextField GenreInput;
    private javax.swing.JLabel GenreLBL;
    private javax.swing.JTextField IDInput;
    private javax.swing.JTextField PublisherInput;
    private javax.swing.JLabel PublisherLBL;
    private javax.swing.JTextField TitleInput;
    private javax.swing.JLabel TitleLBL;
    private javax.swing.JTextField YearInput;
    private javax.swing.JLabel YearLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processButton;
    // End of variables declaration                   
}
